name: Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./"
          use_pyproject: true
