name: pg_format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pgformatter
        run: |
          sudo apt install pgformatter=5.2-1 -y
      - name: Run
        run: |
          find ./ -type f -name "*.sql" -exec pg_format -i {} \;
