name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint_ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - name: Install dependencies
        run: |
          pip install .
      - name: Format
        run: |
          ruff format . --check
      - name: Lint
        run: |
          ruff check .

  lint_mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - name: Install dependencies
        run: |
          pip install .
      - name: Run mypy
        run: |
          mypy ./

  deploy:
    runs-on: ubuntu-latest
    needs: [lint_ruff, lint_mypy]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/SpaceCases
            git fetch origin
            git reset --hard origin/master
            sudo systemctl restart spacecases
